[tool.poetry]
name = "fabric-naive"
version = "0.1.0"
description = ""
authors = ["jeongsukchul <tjrcjf410@snu.ac.kr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
